### PR TITLE
Module Structural Improvements & Testing

### PR DESCRIPTION
**Pull request by sheldonhull**
Have found great use as an adhoc tool for quick console helpers. Figured I'd try again after losing some changes and tests I tried to send you the first time (lost local repo). 

This includes some testing framework and structure I've pulled from the fantastic PSFramework that includes analytics tests and more. 
Would like to see if this seems an improvement, as MIT licensing also opens it up for easier reuse for me and others. Thanks for this cool tool. I plan on some future tweaks to add a banner title option and description of the selection etc, but figured I'd start with this request.

- Using fantastic framework PSFramework, included some validation and analyzer checks. 
- Pester tests for variety for input and and return situations to validate functionality
- Aligned with powershell naming conventions, but still provided alias output 
- licensing MIT mentioned again to allow easier use for various purposes. 

This is a start at least. Did some testing and everything is working smoothly (not with strict mode , it's off). Will submit as pull request and see if these changes are accepted. If so, i think an updated  PSGallery build would be good to include in here as well.

### CODE REVIEW

**Comment by sheldonhull** [comment]
Just following up to see if this came through to you? The license is esp crucial for many of us who have strict requirements on licensing, so I'm hoping that this addition will help improve for other who could then use. If you have any questions let me know! Cheers!

**Comment by sheldonhull** [comment]
Any feedback? I know you've probably been busy but just wanted to see if you could take a few minutes and take a peek at the new structure I provided (using PSFramework)

**Comment by chrisseroka** [comment]
Hi Sheldon,

Really sorry for late answer, but I had some time off. I'm checking it
right now.

Best regards

pon., 18 cze 2018 o 19:01 SheldonH <notifications@github.com> napisał(a):

**Comment by chrisseroka** [comment]
In general I must say that the code is much more complicated. I see the value of PSFramework but rather for bigger projects that this one.  I would prefer to keep it simple.

**Comment by sheldonhull** [comment]
@chrisseroka  understood. Would you be ok with at least adding the MIT license, and I can just create a separate project to extend with some of the additional test methods, title, and framework stuff? If that's ok with you I could publish that separately, with attribution to you as original creator of course. Probably call it something like PSF-Menu or something similar but different. 

Cool with you?

Thanks for your time!

**Comment by chrisseroka** [comment]
Sure, that's OK. I will add MIT license with other changes, but you can
already create separate project

śr., 27 cze 2018 o 15:56 SheldonH <notifications@github.com> napisał(a):

**Comment by sheldonhull** [comment]
Much appreciated! Thanks for the inspiration!

**Pull request closed without merging**
